### ISSUE TITLE
发现Http版本的相对于TCP版本的有诸多限制，感觉就是一个半成品

### ISSUE THREAD

**Issue by LeisurelyYang** [aliyunmq/mq-http-go-sdk#1]
1.在开发过程中使用golang版本的sdk,遇到消息超时确认问题，发现http的不可以设置消息消费确认超时时间
2.遇到需要删除消息的场景，发现HTTP版本的不可以重置消费位点
3.还有许多莫名奇妙的问题，真的很难生产环境使用

**Comment by zhouxinyu** [comment]
你好：
1. 新版本SDK已经可以设置超时时间。
2. 可以在控制台上进行重制。
3. 有其它问题欢迎反馈。
