### ISSUE TITLE
请教版本问题

### ISSUE THREAD

**Issue by ACoderHIT** [aliyunmq/mq-http-go-sdk#4]
目前首页readme已经写到1.0.3了，但是release版本还是1.0.1，我运行的是1.0.3的example，发现没有1.0.3的tag，所以能不能统一下。。

还有首页就有错别字 Note for .... 而不是Not for吧.....

**Comment by aliyunmq** [comment]
您好：1.0.3增加了顺序特性，但是MQ服务这边顺序特性在灰度中，所以如果您使用1.0.3请不要使用顺序特性。

**Comment by aliyunmq** [comment]
您也可以直接使用1.0.1的tag代码。

**Comment by ACoderHIT** [comment]
ok，如果说1.0.1出队是无序的，会不会有某些消息一直处于滞留的场景？

**Comment by zhouxinyu** [comment]
你好，已发布，可以go get 1.0.3
