### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by xuhaoxian** [aliyunmq/mq-http-go-sdk#6]
http版本使用大量publish会出现 socket: too many open files。可以提供tcp版本吗

**Comment by jilinhao** [comment]
> http版本使用大量publish会出现 socket: too many open files。可以提供tcp版本吗
大神有办法不？？

**Comment by zhouxinyu** [comment]
有TCP版本可以用的。参考官方文档：https://help.aliyun.com/document_detail/124693.html?spm=a2c4g.11174283.6.591.22d7347dksxaGZ
