### ISSUE TITLE
sample示例有隐患

### ISSUE THREAD

**Issue by shengzhch** [aliyunmq/mq-http-go-sdk#7]
endChan := make(chan int)
	respChan := make(chan mq_http_sdk.ConsumeMessageResponse)
	errChan := make(chan error)

都是用的无缓冲channel，当mqConsumer.ConsumeMessage()函数遇到网络延迟时，超过35秒才能写入结果时，而读取结果的goroutinue已经结束，出现deadlock。最好加上缓冲

fasthttp的取得超时是35秒，但还是有隐患

**Comment by zhouxinyu** [comment]
你好，sample仅用于参考，不能用于生产，很难覆盖所有的场景哈。
